"""add timestamp column for future mobile offline sync

Revision ID: 51eb26617ad1
Revises: be5d088619d5
Create Date: 2026-09-05 01:12:06.104914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eb26617ad1'
down_revision: Union[str, Sequence[str], None] = 'be5d088619d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_accounts_timestamp'), 'accounts', ['timestamp'], unique=False)
    op.add_column('assets', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_assets_timestamp'), 'assets', ['timestamp'], unique=False)
    op.add_column('cards', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_cards_timestamp'), 'cards', ['timestamp'], unique=False)
    op.add_column('categories', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_categories_timestamp'), 'categories', ['timestamp'], unique=False)
    op.add_column('exchange_rates', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_exchange_rates_timestamp'), 'exchange_rates', ['timestamp'], unique=False)
    op.add_column('installment_plans', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_installment_plans_timestamp'), 'installment_plans', ['timestamp'], unique=False)
    op.add_column('investment_transactions', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_investment_transactions_timestamp'), 'investment_transactions', ['timestamp'], unique=False)
    op.add_column('transactions', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_column('transactions', 'timestamp')
    op.drop_index(op.f('ix_investment_transactions_timestamp'), table_name='investment_transactions')
    op.drop_column('investment_transactions', 'timestamp')
    op.drop_index(op.f('ix_installment_plans_timestamp'), table_name='installment_plans')
    op.drop_column('installment_plans', 'timestamp')
    op.drop_index(op.f('ix_exchange_rates_timestamp'), table_name='exchange_rates')
    op.drop_column('exchange_rates', 'timestamp')
    op.drop_index(op.f('ix_categories_timestamp'), table_name='categories')
    op.drop_column('categories', 'timestamp')
    op.drop_index(op.f('ix_cards_timestamp'), table_name='cards')
    op.drop_column('cards', 'timestamp')
    op.drop_index(op.f('ix_assets_timestamp'), table_name='assets')
    op.drop_column('assets', 'timestamp')
    op.drop_index(op.f('ix_accounts_timestamp'), table_name='accounts')
    op.drop_column('accounts', 'timestamp')
    # ### end Alembic commands ###
