"""add users and multi-tenant user_id columns

Revision ID: be5d088619d5
Revises: 651d236e3fcc
Create Date: 2026-09-04 17:38:01.825613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5d088619d5'
down_revision: Union[str, Sequence[str], None] = '651d236e3fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_foreign_key('accounts_user_id_fkey', 'accounts', 'users', ['user_id'], ['id'])
    op.add_column('assets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_asset_ticker_type'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_unique_constraint('uq_asset_user_ticker_type', 'assets', ['user_id', 'ticker', 'type'])
    op.create_foreign_key('assets_user_id_fkey', 'assets', 'users', ['user_id'], ['id'])
    op.add_column('card_statements', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_card_statements_user_id'), 'card_statements', ['user_id'], unique=False)
    op.create_foreign_key('card_statements_user_id_fkey', 'card_statements', 'users', ['user_id'], ['id'])
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_foreign_key('cards_user_id_fkey', 'cards', 'users', ['user_id'], ['id'])
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_unique_constraint('uq_category_user_name', 'categories', ['user_id', 'name'])
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'])
    op.add_column('installment_plans', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_installment_plans_user_id'), 'installment_plans', ['user_id'], unique=False)
    op.create_foreign_key('installment_plans_user_id_fkey', 'installment_plans', 'users', ['user_id'], ['id'])
    op.add_column('investment_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_investment_transactions_user_id'), 'investment_transactions', ['user_id'], unique=False)
    op.create_foreign_key('investment_transactions_user_id_fkey', 'investment_transactions', 'users', ['user_id'], ['id'])
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint('investment_transactions_user_id_fkey', 'investment_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_investment_transactions_user_id'), table_name='investment_transactions')
    op.drop_column('investment_transactions', 'user_id')
    op.drop_constraint('installment_plans_user_id_fkey', 'installment_plans', type_='foreignkey')
    op.drop_index(op.f('ix_installment_plans_user_id'), table_name='installment_plans')
    op.drop_column('installment_plans', 'user_id')
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.drop_constraint('uq_category_user_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'user_id')
    op.drop_constraint('cards_user_id_fkey', 'cards', type_='foreignkey')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_column('cards', 'user_id')
    op.drop_constraint('card_statements_user_id_fkey', 'card_statements', type_='foreignkey')
    op.drop_index(op.f('ix_card_statements_user_id'), table_name='card_statements')
    op.drop_column('card_statements', 'user_id')
    op.drop_constraint('assets_user_id_fkey', 'assets', type_='foreignkey')
    op.drop_constraint('uq_asset_user_ticker_type', 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.create_unique_constraint(op.f('uq_asset_ticker_type'), 'assets', ['ticker', 'type'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'user_id')
    op.drop_constraint('accounts_user_id_fkey', 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_column('accounts', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
