"""add recurring expenses

Revision ID: ca01b560ea1f
Revises: 51eb26617ad1
Create Date: 2026-09-05 15:06:03.042037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca01b560ea1f'
down_revision: Union[str, Sequence[str], None] = '51eb26617ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('last_generated_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_recurring_expense_amount_positive'),
    sa.CheckConstraint('day_of_month BETWEEN 1 AND 31', name='ck_recurring_expense_day'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_timestamp'), 'recurring_expenses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_recurring_expenses_user_id'), 'recurring_expenses', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('recurring_expense_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_recurring_expense_period', 'transactions', ['recurring_expense_id', 'date'])
    # Nombre explícito -- el proyecto no define una naming convention en Base.metadata, así que
    # autogenerate deja `None` acá, lo que rompe el downgrade (Postgres exige nombre para DROP
    # CONSTRAINT). Mismo criterio que transactions_investment_transaction_id_fkey.
    op.create_foreign_key(
        'transactions_recurring_expense_id_fkey',
        'transactions', 'recurring_expenses', ['recurring_expense_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_recurring_expense_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('uq_recurring_expense_period', 'transactions', type_='unique')
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'recurring_expense_id')
    op.drop_index(op.f('ix_recurring_expenses_user_id'), table_name='recurring_expenses')
    op.drop_index(op.f('ix_recurring_expenses_timestamp'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
